name: gogoto infraestrutura

on:
  push:
    branches: [ "feature/github-actions", "master" ]
env:
  AZURE_FUNCTIONAPP_NAME_REDIRECT: "redirectToDestinationUrl"
  AZURE_FUNCTIONAPP_NAME_CREATE: "createShortenedUrl"
  AZURE_FUNCTIONAPP_NAME_DELETE: "deleteShortenedUrl"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./bin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3  # Substitua por sua versão Go

      - name: Run make build
        run: make build

  setup:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Terraform Init - Avaliando mudanças para serem implementadas
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Init - Iniciando
        run: terraform init

  apply:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Terraform apply - Aplicando mudança de infraestrutura na Azure
        run: |
          terraform apply -auto-approve

  deploy_create_shortened_url:
    runs-on: ubuntu-latest
    need: apply
    steps:
      - name: Deploy função: createShortenedUrl
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_CREATE }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

  deploy_delete_shortened_url:
    runs-on: ubuntu-latest
    need: apply
    steps:
      - name: Deploy função: deleteShortenedUrl
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_DELETE }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

  deploy_redirect_to_destination_url:
    runs-on: ubuntu-latest
    need: apply
    steps:
      - name: Deploy função: redirectToDestinationUrl
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_REDIRECT }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
