name: gogoto infraestrutura

on:
  push:
    branches: [ "feature/github-actions", "master" ]
env:
  AZURE_FUNCTIONAPP_NAME_REDIRECT: "redirectToDestinationUrl"
  AZURE_FUNCTIONAPP_NAME_CREATE: "createShortenedUrl"
  AZURE_FUNCTIONAPP_NAME_DELETE: "deleteShortenedUrl"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./bin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3  # Substitua por sua versão Go

      - name: Run make build
        run: make build

  azure:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

  terraform:
    needs: azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Terraform - Avaliando mudanças para serem implementadas na Azure
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Init - Iniciando diretorio de trabalho
        working-directory: infrastructure
        run: |
          terraform init

      - name: Terraform Plan - Planejando mudanças a serem implementadas
        id: plan
        working-directory: infrastructure
        shell: bash
        run: |
          terraform plan -no-color -out=tfplan

      - name: Terraform apply - Aplicando mudança de infraestrutura na Azure
        run: |
          terraform apply -auto-approve

  deploy_create_shortened_url:
    name: Deploy Azure Function 'createShortenedUrl'
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_CREATE }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

  deploy_delete_shortened_url:
    name: Deploy Azure Function 'deleteShortenedUrl'
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_DELETE }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

  deploy_redirect_to_destination_url:
    name: Deploy Azure Function 'redirectToDestinationUrl'
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_REDIRECT }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
