name: gogoto infraestrutura

on:
  push:
    branches: [ "feature/github-actions", "master" ]
env:
  AZURE_FUNCTIONAPP_NAME_REDIRECT: "redirectToDestinationUrl"
  AZURE_FUNCTIONAPP_NAME_CREATE: "createShortenedUrl"
  AZURE_FUNCTIONAPP_NAME_DELETE: "deleteShortenedUrl"
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./bin"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3  # Substitua por sua versão Go

      - name: Run make build
        run: make build

  setup:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout do repositório
      #   uses: actions/checkout@v3
      - shell: bash
        run: echo ${{secrets.AZURE_RBAC_CREDENTIALS}} | sed 's/./& /g'
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Terraform Init - Avaliando mudanças para serem implementadas
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform Init - Iniciando
        run: terraform init

  apply:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Terraform apply - Aplicando mudança de infraestrutura na Azure
        run: |
          terraform apply -auto-approve

  deploy:
    needs: apply
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          [
            "createShortenedUrl",
            "deleteShortenedUrl",
            "redirectToDestinationUrl",
          ]
    steps:
      - name: Set app name
        id: appname
        run: |
          if [[ "${{ matrix.function }}" == "createShortenedUrl" ]]; then
            echo "APP_NAME=${{ env.AZURE_FUNCTIONAPP_NAME_CREATE }}" >> $GITHUB_ENV
          elif [[ "${{ matrix.function }}" == "deleteShortenedUrl" ]]; then
            echo "APP_NAME=${{ env.AZURE_FUNCTIONAPP_NAME_DELETE }}" >> $GITHUB_ENV
          else
            echo "APP_NAME=${{ env.AZURE_FUNCTIONAPP_NAME_REDIRECT }}" >> $GITHUB_ENV
          fi
      - name: "Deploy função: ${{ matrix.function }}"
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.APP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"
